version: '3'
services:
  db:
    image: postgres:13-alpine
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d/

  email_service:
    depends_on:
      - db
    build:
      context: apps/email_service
    environment:
      SECRET_KEY_BASE: "S3croj/0ZcfwSMYKKhzNrRnCFcdSNVrrO+Pt1nnRYdtiOWkQj08hUVwMdRkk8BL+"
      DATABASE_URL: "postgres://docker:123@db/email_service_db"
      PHX_SERVER: true
    ports:
      - "4001:4000"

  auth_service:
    depends_on:
      - db
      - email_service
    build:
      context: apps/auth_service
    environment:
      EMAIL_SERVICE_URL: "http://email_service:4000"
      SECRET_KEY_BASE: "Q2MF2Q+lE9uNqRmylF6LMV4u7sYgpaA/FinEzUTKQo5ea+Uci0OZwnKb+EcatGp3"
      DATABASE_URL: "postgres://docker:123@db/auth_service_db"
      PHX_SERVER: true
    ports:
      - "4002:4000"