name: "email"

on:
  push:
    # run the workflow only on changes
    # to the email route and email workflow
    paths:
      - "apps/email_service/**"
      - ".github/workflows/email.yaml"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.12.3]
        otp: [23.2.7]

    services:
      db:
        image: postgres:12-alpine
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: email_service_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v1
        id: mix-cache
        with:
          path: apps/email_service/deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/apps/email_service/mix.lock')) }}

      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          cd apps/email_service
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check Formatting
        run: |
          cd apps/email_service
          mix format --check-formatted

      - name: Compile project without warnings
        run: |
          cd apps/email_service
          mix compile --warnings-as-errors

      - name: Run tests
        run: |
          cd apps/email_service
          EMAIL_SERVICE_URL=http://nope mix test
